### ISSUE TITLE
Prefix in name

### ISSUE THREAD

**Issue by jvdoorn** [RuItech/HiveMind#14]
I'm not sure if this project is mainly focussing on English/American people in which case this issue might be irrelevant but a lot of Dutch people (and other Europeans) have a prefix in their name. I personally always find it annoying when websites don't support this. Let me give an example:

Let's say you're called "Jurrien van Dam", a lot of sites only offer a first name and last name field so you'd get:
`Jurrien` and `van Dam` or `Jurrien` and `Dam, van`
Both of those are not perfect as the last name in the first case will be put (alphabetically) near "v", whilst it should be at "d" and in the second case you expect people to properly sort their own last name (which they won't).

So I suggest adding a prefix field to the [`Profile` model](https://github.com/RuItech/HiveMind/blob/master/hivemind/modules/api/models/profile.py). If you think this is worth doing so I'll gladly create a PR for it.

**Comment by DavisRayM** [comment]
I'm personally all up for this idea as this project is meant to be used by any and all School Clubs that may need it. But,  I would prefer that the new field be called middle name. As prefix in my understanding may refer to 'Mr' , 'Mrs', 'Sir' and so on. Other than that i'm fine with this being added into the package, create a pr whenever your ready.

**Comment by jvdoorn** [comment]
My bad, I translated it the wrong way, the word I was looking for is "preposition" or "family name preposition". I'll also add a prefix though so people can choose their prefix (such as "Mr.", "Mrs.", etc.).

I'll start working on it.
