### ISSUE TITLE
Create Payments Model

### ISSUE THREAD

**Issue by DavisRayM** [RuItech/HiveMind#2]
- [x] Create [Payments](https://github.com/RuItech/HiveMind/blob/master/docs/architecture.md#models) Model.
- [x] Create Tests for Payments Model

**Comment by DavisRayM** [comment]
For an example on how to implement a model check out the [Profile Model](https://github.com/RuItech/HiveMind/blob/master/hivemind/modules/api/models/profile.py) and for tests check out the [Profile Model Tests](https://github.com/RuItech/HiveMind/blob/master/hivemind/modules/api/tests/models/test_profile.py)

**Comment by Mse-lunani** [comment]
Ima work on this

**Comment by DavisRayM** [comment]
@Mse-lunani Alright i'll assign this to you. Contact me if you need any clarifications on the model fields or anything else.
