### ISSUE TITLE
Create News Model

### ISSUE THREAD

**Issue by DavisRayM** [RuItech/HiveMind#4]
- [x] Create [News](https://github.com/RuItech/HiveMind/blob/master/docs/architecture.md#models) Model.
- [x] Create Tests for News Model

**Comment by DavisRayM** [comment]
For an example on how to implement a model check out the [Profile Model](https://github.com/RuItech/HiveMind/blob/master/hivemind/modules/api/models/profile.py) and for tests check out the [Profile Model Tests](https://github.com/RuItech/HiveMind/blob/master/hivemind/modules/api/tests/models/test_profile.py)

**Comment by ZeroCoolHacker** [comment]
Put a requirements.txt file there

**Comment by DavisRayM** [comment]
@ZeroCoolHacker Sorry, not quite sure why that would be required ? Doesn't the Pipfile ([Pipenv](https://pipenv.readthedocs.io/en/latest/))  handle all the requirements for the app ?

**Comment by ZeroCoolHacker** [comment]
I am sorry i had never used that before.

**Comment by DavisRayM** [comment]
@ZeroCoolHacker  No worries 😄

**Comment by jvdoorn** [comment]
@ZeroCoolHacker Are you working on this? If not I'll start working on it.

**Comment by DavisRayM** [comment]
@Argetan no one is currently, working on this. Feel free to start it.

**Comment by jvdoorn** [comment]
Sure thing.

**Comment by ZeroCoolHacker** [comment]
> Sure thing.

I am busy right now with other projects @Argetan You better do it. Best of luck!
